/**************************************************************************
   NET NAME    : default 
   GENERATED AT: Tue Nov 30 15:38:20 2004
 

   SNNS VERSION: V1.4-3D
   PURPOSE     : constant declarators and default values
   NOTES       : this file is generated by snns2c

   UPDATE FUNC : Serial_Order
   LEARN FUNC  : Std_Backpropagation
   AUTHOR      : Kais Brahim
   CHANGED BY  : Dietmar Posselt
   VERSION     : 1.0

             Copyright (c) 1990-1993  SNNS Group, IPVR, Univ. Stuttgart, FRG

*****************************************************************************/ 
 

#define     NO_OF_UNITS        46
#define     NO_OF_LINKS        528
#define     NO_OF_UNIT_TYPES   0
#define     NO_OF_SITE_TYPES   0
#define     MIN_UNIT_NO        1
#define     MAX_UNIT_NO        46
#define     NO_OF_IN_UNITS      22
#define     NO_OF_OUT_UNITS     2
#define     NO_OF_LINK_ENTRIES  24



#define     UPDATE_FUNC       (FunctionPtr)UPDATE_serialPropagate



#define     NET_FILE_VERSION    "V1.4-3D"
#define     NET_NAME           "default"
#define     PAT_IN_FILE        "default.pat"
#define     PAT_RES_FILE       "default.res"



typedef float  *Patterns; 

int Init_Net (void);
int Load_Pattern_File (FILE *pat_file, Patterns *in_patterns,
                                        Patterns *out_patterns);
int Propagate_Pattern_Array (Patterns in_patterns,
                            Patterns out_pattern);
int Propagate_Pattern (float *in_pattern, float *out_pattern);
int Write_Pattern_Arrays (FILE *filehandle, int start_pattern,
                          Patterns in_pat, Patterns out_pat);
int Write_Pattern (FILE *filehandle, float *in_pattern,
                                    float *out_pattern);
char *err_chk(int err);




